---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
polling_url: |
  https://gtfs.transitnownash.org/stops/{{ stop_id }}.json
  https://gtfs.transitnownash.org/stops/{{ stop_id }}/trips.json?per_page=200
  https://gtfs.transitnownash.org/routes.json
  https://gtfs.transitnownash.org/realtime/vehicle_positions.json
  https://gtfs.transitnownash.org/realtime/trip_updates.json
  https://gtfs.transitnownash.org/realtime/alerts.json
polling_headers: ''
id: 91940
custom_fields:
- keyname: stop_id
  field_type: string
  name: Stop ID
  description: The code for the stop to monitor
  placeholder: PORGRESF
name: WeGo Public Transit Next Bus
refresh_interval: 15
